version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-text-compose-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    command: npm run dev
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

